### ISSUE TITLE
Issue with OnceAll(1) call when at(1) use 

### ISSUE THREAD

**Issue by inarty** [avsokolov/soft-touch#1]
There is issue with OnceAll(1) calling when at(1) setting. Code Example: 
https://codepen.io/inarty/pen/QxvMjX?editors=0010

Looks like a problem with improper POS calculation. Same with 0.5 calling onceAll with value 0.518. but it should be 0.5, because I've set it to 0.5.

It's critical for me, because when user in UI set animation to specific value it can compare POS like (if POS < = 0.5) and get unexpected result, because pos is 0.518 instead.

**Comment by avsokolov** [comment]
fixed
